#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

cp system/topoSetDict.refineLevel1 system/topoSetDict
runApplication topoSet
mv log.topoSet log.topoSetLevel1

runApplication refineMesh -dict refineMeshDict.level1 -overwrite
mv log.refineMesh log.refineMeshLevel1

cp system/topoSetDict.refineLevel2 system/topoSetDict
runApplication topoSet
mv log.topoSet log.topoSetLevel2

runApplication refineMesh -dict refineMeshDict.level2 -overwrite
mv log.refineMesh log.refineMeshLevel2
runApplication checkMesh
#runApplication fsinetMultiStepFoam3D
runApplication decomposePar
runApplication mpirun dynaPorousNetFoam -parallel
#runApplication dynaPorousNetFoam
